spring:
  application:
    name: Afripay
  
  data:
    redis:
      host: localhost
      port: 6379
      
  datasource:
    url: jdbc:postgresql://localhost:5432/AfriPay
    username: postgres
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true