CREATE TABLE transactions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rrn          VARCHAR(255),
    pan          VARCHAR(255),
    amount       DECIMAL,
    status       VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);